source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'
use_frameworks!

target 'Navigation' do
  
  pod 'SnapKit', '~> 5.0.0'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'KeychainAccess'

end

target 'StorageService' do

end
